# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Repofleet < Formula
  desc "Issue-centered CLI tool for managing Git workflows across multiple repositories"
  homepage "https://github.com/mehranzand/repofleet"
  version "0.5.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mehranzand/repofleet/releases/download/v0.5.2/repofleet_darwin_amd64.tar.gz"
      sha256 "bc7e5a881ce68a9ec7bed43a6ba372b071d960d7e2c96fedfccdfcd79df2088b"

      define_method(:install) do
        bin.install "rf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mehranzand/repofleet/releases/download/v0.5.2/repofleet_darwin_arm64.tar.gz"
      sha256 "211c303fcbfbbcf1fd0eba0cea52c52fefdb5dc2bc0182073af54094d4a2679f"

      define_method(:install) do
        bin.install "rf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mehranzand/repofleet/releases/download/v0.5.2/repofleet_linux_amd64.tar.gz"
      sha256 "31d73a285ed98363588802e19ccaa26b755ef9a5d441043ec888bdd7cb05f73c"
      define_method(:install) do
        bin.install "rf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mehranzand/repofleet/releases/download/v0.5.2/repofleet_linux_arm64.tar.gz"
      sha256 "16ddcb2aa168f15ccdb610b91f8a91bf12e73d88e85166488f92d8e5659ce8cc"
      define_method(:install) do
        bin.install "rf"
      end
    end
  end
end
