# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Repofleet < Formula
  desc "Issue-centered CLI tool for managing Git workflows across multiple repositories"
  homepage "https://github.com/mehranzand/repofleet"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mehranzand/repofleet/releases/download/v0.4.0/repofleet_darwin_amd64.tar.gz"
      sha256 "530fbe8d9a4719a08ba6979c14588921607c7561a838b0bd411bf56aea05148a"

      define_method(:install) do
        bin.install "rf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mehranzand/repofleet/releases/download/v0.4.0/repofleet_darwin_arm64.tar.gz"
      sha256 "f41e55dbc2a9a39f34bdd466998a8cc0628472a494c8d0acf2663285549197cd"

      define_method(:install) do
        bin.install "rf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mehranzand/repofleet/releases/download/v0.4.0/repofleet_linux_amd64.tar.gz"
      sha256 "e82d9bef317f8bbf5cf91f85818070c2e553691ec02399caed5c1d480747c355"
      define_method(:install) do
        bin.install "rf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mehranzand/repofleet/releases/download/v0.4.0/repofleet_linux_arm64.tar.gz"
      sha256 "2d261fa4f1c537b2d0c1987141335fc42e8c10892ecfdaf50ee8adcbe73edacd"
      define_method(:install) do
        bin.install "rf"
      end
    end
  end
end
