# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Repofleet < Formula
  desc "Issue-centered CLI tool for managing Git workflows across multiple repositories"
  homepage "https://github.com/mehranzand/repofleet"
  version "0.5.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mehranzand/repofleet/releases/download/v0.5.4/repofleet_darwin_amd64.tar.gz"
      sha256 "262850dd12382f7fc698b117cc54663befb747fd78fa8d369f7ac28eaa1ea64b"

      define_method(:install) do
        bin.install "rf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mehranzand/repofleet/releases/download/v0.5.4/repofleet_darwin_arm64.tar.gz"
      sha256 "98893744d1784c32b4831b6eb1782426f222f20639fa9f84a41e0fa4b03daeff"

      define_method(:install) do
        bin.install "rf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mehranzand/repofleet/releases/download/v0.5.4/repofleet_linux_amd64.tar.gz"
      sha256 "c39718c6092f6c85fa314b4ae94ac1b929ce3ee654a24029973a0dc69321ef07"
      define_method(:install) do
        bin.install "rf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mehranzand/repofleet/releases/download/v0.5.4/repofleet_linux_arm64.tar.gz"
      sha256 "467ebf1bc0c394e479505b0b61790e4e1dd09182efff646a8e08f73c94979916"
      define_method(:install) do
        bin.install "rf"
      end
    end
  end
end
